import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'docs', 'trivia');
const OUT = path.join(ROOT, 'trivia.js');

function parseFile(file, difficulty) {
  const text = fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
  const blocks = text
    .split(/\n(?=### \d+\. )/)
    .filter((b) => /^### \d+\. /m.test(b));

  return blocks.map((block) => {
    const headerMatch = block.match(/^### (\d+)\.\s*(.+?)\s*$/m);
    if (!headerMatch) throw new Error(`No header in block:\n${block.slice(0, 80)}`);
    const number = parseInt(headerMatch[1], 10);
    const question = headerMatch[2].trim();

    const ansMatch = block.match(
      /\*\*R[ăa]spuns:\*\*\s*([\s\S]+?)(?=\n\*\*|\n###|\n*$)/
    );
    const answer = ansMatch ? ansMatch[1].trim() : '';

    const refMatch = block.match(
      /\*\*Referin[țt][ăa]:\*\*\s*([\s\S]+?)(?=\n\*\*|\n###|\n*$)/
    );
    let reference = '';
    let quote = '';
    if (refMatch) {
      const refText = refMatch[1].trim();
      const dashSplit = refText.split(/\s+—\s+/);
      reference = dashSplit[0].trim();
      if (dashSplit.length > 1) {
        const rest = dashSplit.slice(1).join(' — ');
        const qm = rest.match(/\*„([\s\S]+?)["”]\*/);
        if (qm) quote = qm[1].trim();
        else reference = refText;
      }
    }

    return {
      id: `${difficulty}-${number}`,
      number,
      question,
      answer,
      reference,
      quote,
    };
  });
}

const trivia = {
  easy: parseFile(path.join(SRC, 'easy.md'), 'easy'),
  medium: parseFile(path.join(SRC, 'medium.md'), 'medium'),
  hard: parseFile(path.join(SRC, 'hard.md'), 'hard'),
};

for (const [k, arr] of Object.entries(trivia)) {
  if (arr.length !== 40) {
    console.warn(`WARN: ${k} has ${arr.length} questions (expected 40)`);
  }
  for (const q of arr) {
    if (!q.question || !q.answer) {
      console.warn(`WARN: ${q.id} missing data:`, q);
    }
  }
}

const out =
  `// Auto-generated by tools/parse-trivia.mjs — do not edit by hand.\n` +
  `window.TRIVIA = ${JSON.stringify(trivia, null, 2)};\n`;
fs.writeFileSync(OUT, out, 'utf8');
console.log(
  `Wrote trivia.js: easy=${trivia.easy.length}, medium=${trivia.medium.length}, hard=${trivia.hard.length}`
);
